# Regenerate inst/extdata/demo: a synthetic 12-boring LIF site with EC, HP,
# and emission colour channels. Entirely simulated by lif_simulate(); no
# relation to any real site. Run from the package root:
#
#   devtools::load_all(); source("data-raw/make_demo.R")

out <- file.path("inst", "extdata", "demo")
unlink(out, recursive = TRUE)
lif_simulate(n_borings = 12, dir = out, seed = 20260904, extent = 220,
             origin = c(1000, 2000), interval = 0.25, depth_range = c(24, 38),
             msl = 150, verbose = TRUE)

writeLines(c(
  "# demo: synthetic 12-boring LIF site",
  "",
  "Generated by `data-raw/make_demo.R` with `lif_simulate(seed = 20260904)`.",
  "Two overlapping fluorescence lobes near the centre of a 220 ft x 220 ft",
  "site, sampled every 0.25 ft to 24-38 ft, with EC (mS/m), HP (psi), and an",
  "emission-colour channel. The data are simulated and have no relation to",
  "any real site.",
  "",
  "| Column      | Raw header  | Description                          |",
  "|-------------|-------------|--------------------------------------|",
  "| signal      | Signal      | LIF response, %RE                    |",
  "| ec          | EC.Value    | Electrical conductivity, mS/m        |",
  "| hp          | HP.PresDown | Hydraulic push pressure, psi         |",
  "| color       | color       | Emission-wavelength hex colour       |"
), file.path(out, "README.md"))
